name: freezed_bug_expr_body
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  freezed_annotation: ^0.15.0

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^0.15.1+1
  lints: ^1.0.0
  test: ^1.16.0
